### ISSUE TITLE
Protobuf is too new

### ISSUE THREAD

**Issue by ravenium** [DoctorOctagonapus/HA-Eufy-Integration#1]
I think this is a sort of losing cause (eventually), but the 12.8 release of hass broke this integration (again).

Reason is that it doesn't work with newer protobufs.  Had to peg the versioning at 3.20.  

Not a huge change, I can submit a PR for the heck of it!

**Comment by DoctorOctagonapus** [comment]
Hi, can't say I've noticed a difference myself but thanks. I'll check it out now
